export interface ExplosionCycleResult {
  symbol: string;
  direction: 'LONG' | 'SHORT';
  phase: string;
  phase1Move: string;
  phase2Move: string;
  timeToPhase3: string;
  confidence: number;
  volSurge: string;
  priceChange: number;
  projectedTarget: number;
  scarScore?: number;
  whaleAlert?: boolean;
  prediction?: string;
}

export const BINANCE_FUTURES_PAIRS = [
  'BTCUSDT','ETHUSDT','BNBUSDT','SOLUSDT','XRPUSDT','ADAUSDT','DOGEUSDT','AVAXUSDT',
  'DOTUSDT','MATICUSDT','LINKUSDT','LTCUSDT','UNIUSDT','ATOMUSDT','XLMUSDT','ETCUSDT',
  'TRXUSDT','NEARUSDT','FILUSDT','AAVEUSDT','ALGOUSDT','VETUSDT','ICPUSDT','APTUSDT',
  'ARBUSDT','OPUSDT','INJUSDT','SUIUSDT','SEIUSDT','TIAUSDT','STXUSDT','RUNEUSDT',
  'MKRUSDT','LDOUSDT','SNXUSDT','CRVUSDT','APEUSDT','SANDUSDT','MANAUSDT','AXSUSDT',
  'GALAUSDT','FTMUSDT','GMXUSDT','PERPUSDT','BLURUSDT','PENDLEUSDT','WLDUSDT','CYBERUSDT',
  'HBARUSDT','EGLDUSDT','FLOWUSDT','IMXUSDT','GRTUSDT','1INCHUSDT','ENJUSDT','CHZUSDT',
  'ZECUSDT','DASHUSDT','XMRUSDT','NEOUSDT','IOSTUSDT','ZILUSDT','WAVESUSDT','BALUSDT',
  'COMPUSDT','YFIUSDT','SUSHIUSDT','DYDXUSDT','LRCUSDT','KSMUSDT','CELOUSDT','KAVAUSDT',
  'BANDUSDT','STORJUSDT','SKLUSDT','MASKUSDT','RAREUSDT','TONUSDT','FETUSDT','AGIXUSDT',
  'RENDERUSDT','THETAUSDT','EGPUSDT','HOOKUSDT','MAGICUSDT','HIGHUSDT','JASMYUSDT','CFXUSDT',
  'CKBUSDT','TRUUSDT','LQTYUSDT','OXTUSDT','XVSUSDT','BLZUSDT','DEGOUSDT','ARKUSDT',
  'BNTUSDT','CTKUSDT','BELUSDT','CELRUSDT','IOTXUSDT','COTIUSDT','BAKEUSDT','STMXUSDT',
];
